targetScope = 'resourceGroup'

@description('Default domain generated by the internal Container Apps environment.')
param environmentDefaultDomain string

@description('Static IP address of the internal Container Apps environment.')
param environmentStaticIp string

@description('Virtual network ID used for private DNS linking.')
param virtualNetworkId string

@description('Tags applied to private DNS resources.')
param tags object

resource privateDnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: environmentDefaultDomain
  location: 'global'
  tags: tags
}

resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZone
  name: 'link-${uniqueString(virtualNetworkId, privateDnsZone.name)}'
  location: 'global'
  tags: tags
  properties: {
    virtualNetwork: {
      id: virtualNetworkId
    }
    registrationEnabled: false
  }
}

resource wildcardRecord 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZone
  name: '*'
  properties: {
    ttl: 300
    aRecords: [
      {
        ipv4Address: environmentStaticIp
      }
    ]
  }
}
